---
# Default GitHub labels
- color: ee5253
  name: bug
  description: Something isn't working
- color: 00d2d3
  name: feat
  description: New feature or request
- color: 000000
  name: wontfix
  description: This will not be worked on

# Labels specific
- color: ff6b6b
  name: critical
  description: critical
- color: ff6b6b
  name: database
  description: Everything related to database
- color: 48dbfb
  name: apps
  description: Apps
- color: 5f27cd
  name: packages
  description: Packages
- color: feca57
  name: infra
  description: Infra
- color: 576574
  name: docs
  description: Documentation
- color: #
  name: deps
  description: dependencies
