version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: tsmt-pg
    ports:
      - 5437:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'root']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    volumes:
      - tsmt-postgres:/var/lib/postgresql/data
    networks:
      - tsmt-backend

  jaeger:
    image: jaegertracing/all-in-one
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
      COLLECTOR_OTLP_ENABLED: true
    ports:
      # - 6831:6831/udp
      # - 6832:6832/udp
      # - 5778:5778
      - 5013:16686
      # - 4317:4317
      # - 4318:4318
      - 14250:14250
      # - 14268:14268
      # - 14269:14269
      # - 9411:9411
    networks:
      - tsmt-backend

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      # - 1888:1888 # pprof extension
      # - 8888:8888 # Prometheus metrics exposed by the collector
      # - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      # - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      # - 55679:55679 # zpages extension
    env_file:
      - .env 
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    networks:
      - tsmt-backend

volumes:
  tsmt-postgres:
networks:
  tsmt-backend:
