name: ts-monorepo
region: fra
services:
  - name: api
    github:
      branch: main
      repo: jrobic/ts-monorepo-template
      deploy_on_push: false
    dockerfile_path: apps/api/Dockerfile
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /api
    source_dir: /
    health_check:
      initial_delay_seconds: 0
      period_seconds: 10
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 9
      http_path: /health
      port: 8080
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${ts-monorepo-db.DATABASE_URL}
      - key: APP_PORT
        scope: RUN_TIME
        value: "8080"
      - key: APP_BIND_ADDRESS
        scope: RUN_TIME
        value: "0.0.0.0"
      - key: LOG_LEVEL
        scope: RUN_TIME
        value: debug
      - key: NODE_ENV
        scope: RUN_TIME
        value: production
      - key: APP_ENV
        scope: RUN_TIME
        value: production
      - key: TRACING
        scope: RUN_TIME
        value: "0"

jobs:
  - name: migrate
    kind: PRE_DEPLOY
    instance_size_slug: basic-xxs
    github:
      branch: main
      repo: jrobic/ts-monorepo-template
      deploy_on_push: false
    dockerfile_path: apps/api/Dockerfile.migrate
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${ts-monorepo-db.DATABASE_URL}

databases:
  - name: ts-monorepo-db
    engine: PG
    version: "12"
    production: false
    num_nodes: 1
    size: db-s-dev-database
