#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# if count of files change in git diff HEAD~ is greater than 0
if [ $(git diff --name-only --diff-filter=ACMR HEAD~ -- "**/*.ts" "**/*.tsx" | wc -l) -gt 0 ]; then
  pnpm run test:hook
else
  echo "No files to test"
fi

