# https://docs.github.com/en/actions/learn-github-actions/expressions

name: Pull Request
run-name: Pull Request (@${{ github.actor }})

on:
  pull_request:
    paths-ignore:
      - '*.md'
      - '.*'
      - 'docs/**'

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  load_env_vars:
    name: Load Environment Variables
    runs-on: ubuntu-latest
    steps:
      - uses: freenet-actions/setup-jq@v2
      - run: echo "${{ secrets.CONFIG_JSON }}" | jq -r .
        shell: bash
  build-and-test-api:
    name: Build and Test Api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test-api
        with:
          codacy_project_token: ${{ secrets.CODACY_PROJECT_TOKEN }}
  
  build-and-test-client:
    name: Build and Test Client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test-client
        with:
          codacy_project_token: ${{ secrets.CODACY_PROJECT_TOKEN }}

  e2e:
    name: End to End Tests
    runs-on: ubuntu-latest
    needs: [build-and-test-api, build-and-test-client]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/e2e
